### ISSUE TITLE
Fix typing to not require passing projections for non-pooled connection

### ISSUE THREAD

**Issue by oskardudycz** [event-driven-io/emmett#107]
It seems that something is wrong for that case:
![image](https://github.com/user-attachments/assets/951935a9-ef3b-4963-b0a6-6ca36d4a3a7c)

**Comment by alex-laycalvert** [comment]
Was looking into this and I think this was fixed when the `projections` property was made option for the `PostgresEventStoreOptions`.

**Comment by oskardudycz** [comment]
@alex-laycalver, ah yes, I forgot to close this issue. Thank you for double-checking it 🫡
