### ISSUE TITLE
Browser Only

### ISSUE THREAD

**Issue by dilgerma** [event-driven-io/emmett#124]
Not sure if this is still in scope for Emmet, but running in browser only for prototyping is not supported with Emmet 0.20.x anymore, as it seems the eventstore relies on the commander-library which is using EventEmitter under the hood, which requires Node.

**Comment by oskardudycz** [comment]
@dilgerma, that’s accidental. Apologies for that. I’ll fix it asap and push release (realistically tomorrow). 

The assumption that the core Emmet package should be compatible with both Node.js and Browser remains.

**Comment by oskardudycz** [comment]
@dilgerma the [0.20.2 release](https://github.com/event-driven-io/emmett/releases/tag/0.20.2) is out with the fix. I hope that fixes the issues. I added tests to catch the potential regression. If there's something more happening, I'll appreciate the feedback.
