### ISSUE TITLE
Test: Devise a testing strategy that we can use to reduce duplication among emmet packages

### ISSUE THREAD

**Issue by thiagomini** [event-driven-io/emmett#34]
# Description

As we noted in this [PR](https://github.com/event-driven-io/emmett/pull/33), some test cases are duplicated among our packages. Therefore, when we want to fix them or change something, we have to repeat the same code in multiple files, which is unnecessary and prone to human error. We need to create some sort of matrix testing **or** a testing utility that can be reused across packages to execute the same logical test.

A few things to discuss:

- Each of these "duplicated" tests are located in different packages. For instance, [inMemoryTest](https://github.com/event-driven-io/emmett/blob/main/packages/emmett/src/eventStore/inMemoryEventStore.unit.spec.ts) in `emmet` package and [eventStoreTest](https://github.com/event-driven-io/emmett/blob/main/packages/emmett-esdb/src/eventStore/eventstoreDBEventStore.e2e.spec.ts) in the `emmet-esdb` one. Should we keep them separated?
- What is common between these tests, and what's different? What can we abstract away to facilitate creating tests for future integrations?

## Acceptance Criteria

1. Definition and agreement of a testing strategy that can reduce the boilerplate / duplicate code between tests
2. Implementation of the aforementioned strategy in existing tests

## Additional Information

To inspire this, we can use [ESLint's Testing Helper](https://eslint.org/docs/latest/integrate/nodejs-api#ruletester). They've created a tool to facilitate creating tests that are usually very similar.

**Comment by oskardudycz** [comment]
I was thinking that we could locate such tests into either the main `src` folder or other place. If we had either base class for tests, or generator that would take the event store implementation and some specific settings (e.g. EventStoreDB adds first event at `0` position, while others on `1` ) then this could be quite easy way to deal with permutations. 

Potentially we could have the curried function that would return the `describe` and run it for multiple store implementations.

Of course, we should also eventually document the requirements and test cases in some markdown (and eventually docs).
